name: release-please

on:
    push:
        branches:
            - master
    workflow_dispatch:
        inputs:
            tag:
                description: release git tag manually
                required: false
                type: string

permissions:
    contents: write
    pull-requests: write
    id-token: write

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - uses: googleapis/release-please-action@v4
              id: release
              with:
                  manifest-file: .github/.release-manifest.json
                  config-file: .github/.release-config.json
                  token: ${{ secrets.RELEASE_PLEASE_TOKEN }}

            - uses: actions/checkout@v4
              if: ${{ steps.release.outputs.release_created || github.event.inputs.tag }}

            - uses: actions/setup-node@v4
              if: ${{ steps.release.outputs.release_created || github.event.inputs.tag }}
              with:
                  cache: npm
                  node-version: 24
                  registry-url: "https://registry.npmjs.org"

            - name: Build and publish on VS Code Marketplace
              if: ${{ steps.release.outputs.release_created || github.event.inputs.tag }}
              env:
                  VSCE_PAT: ${{ secrets.VSCE_PAT }}
              run: |
                  npm install --no-fund --no-audit
                  npx vsce package

                  # Only publish if PAT is available and not expired
                  if [ -n "${VSCE_PAT}" ]; then
                    echo "Publishing extension..."
                    npx vsce publish --skip-duplicate || echo "Failed to publish - check if PAT is valid"
                  else
                    echo "VSCE_PAT secret not found - skipping publish"
                  fi
